{ ... }:
{
  users.groups.media.gid = 2000;

  systemd.tmpfiles.rules = [
    "d /srv/media 2775 root media - -"
    "d /srv/media/downloads 2775 root media - -"
    "d /srv/media/downloads/usenet 2775 root media - -"
    "d /srv/media/downloads/usenet/incomplete 2775 root media - -"
    "d /srv/media/downloads/usenet/complete 2775 root media - -"
    "d /srv/media/downloads/usenet/complete/tv 2775 root media - -"
    "d /srv/media/downloads/usenet/complete/movies 2775 root media - -"
    "d /srv/media/downloads/usenet/complete/music 2775 root media - -"
    "d /srv/media/downloads/usenet/complete/books 2775 root media - -"
    "d /srv/media/downloads/torrent 2775 root media - -"
    "d /srv/media/downloads/torrent/incomplete 2775 root media - -"
    "d /srv/media/downloads/torrent/complete 2775 root media - -"
    "d /srv/media/library 2775 root media - -"
    "d /srv/media/library/movies 2775 root media - -"
    "d /srv/media/library/tv 2775 root media - -"
    "d /srv/media/library/music 2775 root media - -"
    "d /srv/media/library/books 2775 root media - -"
    "d /srv/media/library/anime 2775 root media - -"
    "d /srv/media/library/anime/movies 2775 root media - -"
    "d /srv/media/library/anime/tv 2775 root media - -"
    "d /srv/media/library/audiobooks 2775 root media - -"
    "d /srv/media/library/homevideos 2775 root media - -"
    "d /srv/appdata 2770 root media - -"
    "d /srv/appdata/media-mgmt 2770 root media - -"
    "d /srv/appdata/media-mgmt/radarr 2770 root media - -"
    "d /srv/appdata/media-mgmt/sonarr 2770 root media - -"
    "d /srv/appdata/media-mgmt/prowlarr 2770 root media - -"
    "d /srv/appdata/media-mgmt/sabnzbd 2770 root media - -"
    "d /srv/appdata/media-mgmt/bazarr 2770 root media - -"
    "d /srv/appdata/media-mgmt/recyclarr 2770 root media - -"
    "d /srv/appdata/media-mgmt/lidarr 2770 root media - -"
    "d /srv/appdata/media-mgmt/bookshelf 2770 root media - -"
    "d /srv/appdata/media-mgmt/kavita 2770 root media - -"
    "d /srv/appdata/media-mgmt/audiobookshelf 2770 root media - -"
    "d /srv/appdata/media-mgmt/audiobookshelf/config 2770 root media - -"
    "d /srv/appdata/media-mgmt/audiobookshelf/metadata 2770 root media - -"
    "d /srv/appdata/media-mgmt/seerr 2770 kra3 media - -"
  ];
}
