sensor:
  - platform: min_max
    name: "Average Temperature"
    type: mean
    round_digits: 1
    entity_ids:
      - sensor.hue_pir_kitchen_temperature
      - sensor.hue_pir_hallway_temperature
      - sensor.bathroom_occupancy_temperature
      - sensor.bedroom_occupancy_temperature
      - sensor.laundry_occupancy_temperature
      - sensor.toilet_occupancy_temperature

  - platform: min_max
    name: "Average Humidity"
    type: mean
    round_digits: 1
    entity_ids:
      - sensor.bathroom_occupancy_humidity
      - sensor.bedroom_occupancy_humidity
      - sensor.laundry_occupancy_humidity
      - sensor.toilet_occupancy_humidity

  - platform: min_max
    name: "Average Illuminance"
    type: mean
    round_digits: 1
    entity_ids:
      - sensor.hue_pir_kitchen_illuminance
      - sensor.hue_pir_hallway_illuminance
      - sensor.bathroom_occupancy_illuminance
      - sensor.bedroom_occupancy_illuminance
      - sensor.laundry_occupancy_illuminance
      - sensor.toilet_occupancy_illuminance

input_boolean:
  bedroom_is_dark:
    name: Bedroom is dark
  party_mode:
    name: Party mode
    icon: mdi:party-popper
  automations_paused:
    name: Automations paused (manual mode)
    icon: mdi:pause-octagon

template:
  - binary_sensor:
      - name: "House Exits Open Status"
        device_class: opening
        state: >-
          {{ is_state('binary_sensor.yale_front_door_door', 'on')
             or is_state('binary_sensor.hallway_door_contact_contact', 'on')
             or is_state('binary_sensor.patio_door_contact_contact', 'on')
             or is_state('binary_sensor.living_room_window_left_contact_contact', 'on')
             or is_state('binary_sensor.living_room_window_right_contact_contact', 'on')
             or is_state('binary_sensor.bedroom_window_left_contact_contact', 'on')
             or is_state('binary_sensor.bedroom_window_right_contact_contact', 'on')
             or is_state('binary_sensor.kitchen_dining_window_left_contact_contact', 'on') }}
