blueprint:
  name: Door Knock Detection
  description: This blueprint will trigger a custom action when a knock at the door
    is detected by a vibration sensor.
  domain: automation
  author: NotExpectedYet
  homeassistant:
    min_version: 2024.6.0
  input:
    entities:
      name: Entities
      icon: mdi:vibrate
      input:
        virbation_sensor:
          name: Vibration Sensor
          description: The vibration sensor you have attached to the door. This is
            used to detect the knock.
          default: []
          selector:
            entity:
              domain:
              - binary_sensor
              device_class:
              - vibration
              multiple: false
        contact_sensor:
          name: Contact Sensor
          description: The contact sensor you have attached to the door. This is used
            to detect whether the knock was a knock, or just someone opening/closing
            the door.
          default: []
          selector:
            entity:
              domain:
              - binary_sensor
              device_class:
              - door
              - opening
              - window
              multiple: false
    settings:
      name: Settings
      icon: mdi:cog
      input:
        check_duration:
          name: Check Duration
          description: The duration to wait before making sure the door is still in
            the "closed" state. This is best set as low as you can reasonably get
            away with as it will delay the action.
          default:
            hours: 0
            minutes: 0
            seconds: 3
            milliseconds: 0
          selector:
            duration: {}
        no_change_time:
          name: Door Inactive Duration
          description: When the knock is detected, the door must not have changed
            state for this amount of time.
          default: 30
          selector:
            number:
              min: 1.0
              max: 120.0
              unit_of_measurement: seconds
              step: 1.0
              mode: slider
    action_to_trigger:
      name: Action to Trigger
      description: The action to trigger when a knock has been detected.
      default: []
      selector:
        action: {}
    global_condition:
      name: Global condition
      description: Customised condtitions to stop the *entire* automation running.
      default: []
      selector:
        condition: {}
  source_url: https://gist.notexpectedyet.com/notexpectedyet/eb523c5b00624c9da90892e83dee71bc/raw/HEAD/door_knock.yaml
trigger:
- platform: state
  entity_id: !input virbation_sensor
  from: 'off'
  to: 'on'
condition: !input global_condition
variables:
  contact_input: !input contact_sensor
  no_change_time_input: !input no_change_time
  contact_triggered_over_x_ago: '{{(as_timestamp(now()))-(as_timestamp(states[contact_input.split(".")[0]][contact_input.split(".")[1]].last_changed))
    > no_change_time_input }}'
action:
- delay: !input check_duration
- if:
  - condition: template
    value_template: '{{ contact_triggered_over_x_ago }}'
  - condition: state
    entity_id: !input contact_sensor
    state: 'off'
  then: !input action_to_trigger
mode: single
