homeassistant:
  name: Vasudha
  time_zone: Europe/Stockholm
  unit_system: metric
  temperature_unit: C
  country: SE
  currency: SEK
  language: en-GB
  internal_url: "http://192.168.1.33:8123"
  external_url: "https://ha.karunagath.in"
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  packages: !include_dir_named packages

default_config:

network:

http:
  server_host: "0.0.0.0"
  use_x_forwarded_for: true
  trusted_proxies:
    - "127.0.0.1"
    - "10.3.0.0/16"
    - "10.3.2.1"
    - "10.3.2.0/24"

wake_on_lan:

bluetooth:

battery_notes:

ffmpeg:

stream:

prometheus:
  namespace: ha

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

lovelace: !include lovelace.yaml
