---
name: Update Flake Lock

on:
  schedule:
    # daily at 04:00 UTC
    - cron: "0 4 * * *"
  workflow_dispatch: null

permissions:
  contents: write
  pull-requests: write

jobs:
  update-flake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - uses: cachix/install-nix-action@v31

      - name: Update flake.lock
        run: nix flake update

      - name: Open pull request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GH_PAT }}
          commit-message: "chore(deps): bump flake.lock"
          committer: Flake Bot <actions@github.com>
          author: Flake Bot <actions@github.com>
          branch: flake-update
          delete-branch: true
          add-paths: |
            flake.lock
          title: "chore(deps): bump flake.lock"
          body: |
            Automated `nix flake update`.
